### ISSUE TITLE
Additonal addonComponents values

### ISSUE THREAD

**Issue by cyperplex** [DrewViles/helm-charts#1]
Can we add the following options under addonComponents in the values.yaml

ref: https://istio.io/v1.5/docs/setup/install/istioctl/#display-the-configuration-of-a-profile

  kiali:
    enabled: true
  prometheus:
    enabled: true
  tracing:
    enabled: true

**Comment by DrewViles** [comment]
Sure thing, I can get them added in (maybe over the weekend) - in the mean time you can override them by passing in the values section here:

https://github.com/DrewViles/helm-charts/blob/master/istio-operator/values.yaml#L43

**Comment by cyperplex** [comment]
From reading the documentation i can see that ISTIO is no longer grouping the addons as part of the deployment. Closing as this is not revelant.
